--liquibase formatted sql

--changeset admin:000
CREATE TABLE expense_categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    category VARCHAR(50) NOT NULL
);

CREATE TABLE users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(255) NOT NULL,
    email VARCHAR(255) UNIQUE NOT NULL,
    password VARCHAR(255) NOT NULL,
    image_profile VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);



CREATE TABLE expenses(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19,2) NOT NULL,
    description VARCHAR(255) NOT NULL,
    date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    category_id BIGINT NOT NULL,
    payment VARCHAR(55) NOT NULL,
    is_deleted BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT user_id_fk FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT category_id_fk FOREIGN KEY(category_id) REFERENCES expense_categories(id)
);

CREATE TABLE Income(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    amount NUMERIC(19,2) NOT NULL,
    source VARCHAR(255) NOT NULL,
    date DATE NOT NULL,
    user_id BIGINT NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP,
    CONSTRAINT user_id_income_fk FOREIGN KEY(user_id) REFERENCES users(id)
);


CREATE TABLE roles(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    role_type VARCHAR(255)
);

CREATE TABLE user_actions_log(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT NOT NULL,
    action VARCHAR(255) NOT NULL,
    action_on VARCHAR(255) NOT NULL,
    timestamp TIMESTAMP NOT NULL
);

CREATE TABLE user_role(
    user_id BIGINT NOT NULL,
    role_id BIGINT NOT NULL,
    PRIMARY KEY(user_id, role_id),
    CONSTRAINT junction_table_user_id_fk FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT junction_table_role_id_fk FOREIGN KEY(role_id) REFERENCES roles(id)
);


INSERT INTO roles (role_type) VALUES ('ROLE_USER');
INSERT INTO roles (role_type) VALUES ('ROLE_ADMIN');


CREATE TABLE capabilities(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    capability_type VARCHAR(255) NOT NULL
);

CREATE TABLE roles_capabilities(
    role_id BIGINT NOT NULL,
    capability_id BIGINT NOT NULL,
    PRIMARY KEY(role_id, capability_id),
    CONSTRAINT role_id_fk FOREIGN KEY(role_id) REFERENCES roles(id),
    CONSTRAINT capability_id_fk FOREIGN KEY(capability_id) REFERENCES capabilities(id)
);

INSERT INTO capabilities(capability_type) VALUES('EXPENSE_CREATE');
INSERT INTO capabilities(capability_type) VALUES('EXPENSE_DELETE');
INSERT INTO capabilities(capability_type) VALUES('EXPENSE_EDIT');
INSERT INTO capabilities(capability_type) VALUES('EXPENSE_VIEW');
INSERT INTO capabilities(capability_type) VALUES('SYSTEM_MONITOR_INFO');
INSERT INTO capabilities(capability_type) VALUES('AUDIT_LOG_INFO');



INSERT INTO roles_capabilities (role_id, capability_id) VALUES(1,1);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(1,4);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,1);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,2);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,3);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,4);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,5);
INSERT INTO roles_capabilities (role_id, capability_id) VALUES(2,6);


INSERT INTO expense_categories (category) VALUES('Housing');
INSERT INTO expense_categories (category) VALUES('Utilities');
INSERT INTO expense_categories (category) VALUES('Groceries');
INSERT INTO expense_categories (category) VALUES('Transportation');
INSERT INTO expense_categories (category) VALUES('Healthcare');
INSERT INTO expense_categories (category) VALUES('Dining out');
INSERT INTO expense_categories (category) VALUES('Entertainment');
INSERT INTO expense_categories (category) VALUES('Shopping');
INSERT INTO expense_categories (category) VALUES('Education');
INSERT INTO expense_categories (category) VALUES('Personal Care');
INSERT INTO expense_categories (category) VALUES('Subscriptions');
INSERT INTO expense_categories (category) VALUES('Debt Payments');
INSERT INTO expense_categories (category) VALUES('Miscellaneous');

--changeset admin:002
CREATE TABLE reports(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_id VARCHAR(36) NOT NULL,
    csv_file TEXT NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT reports_user_id_fk FOREIGN KEY(user_id) REFERENCES users(id)
);

--changeset admin:003
ALTER TABLE reports
ADD COLUMN is_changed BOOLEAN NOT NULL DEFAULT FALSE;

--changeset admin:004
ALTER TABLE reports
ADD COLUMN ws_sent BOOLEAN NOT NULL DEFAULT FALSE;

--changeset admin:006
CREATE INDEX idx_expense_user_date
ON expenses (user_id, date DESC);

--changeset admin:007
ALTER TABLE reports
ADD COLUMN status VARCHAR(55) NOT NULL DEFAULT 'CREATED';

--changeset admin:008
CREATE TABLE notifications(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sent_at TIMESTAMP NOT NULL,
    csv_file TEXT,
    type VARCHAR(50) NOT NULL,
    user_id BIGINT NOT NULL,
    CONSTRAINT notification_user_id_fk FOREIGN KEY(user_id) REFERENCES users(id)
);
--changeset admin:009
ALTER TABLE reports
DROP COLUMN task_id;

--changeset admin:010
ALTER TABLE reports
ALTER COLUMN status SET DEFAULT 'IDLE';

--changeset admin:011
ALTER TABLE reports
ADD COLUMN worker_lock BOOLEAN NOT NULL DEFAULT FALSE;

--changeset admin:012
CREATE INDEX idx_reports_user_id
ON reports (user_id);

--changeset admin:013
ALTER TABLE reports ALTER COLUMN csv_file DROP NOT NULL;

--changeset admin:014
ALTER TABLE notifications ADD COLUMN is_sent BOOLEAN NOT NULL DEFAULT FALSE;


--changeset admin:015
CREATE INDEX idx_notifications_user_id
ON notifications (user_id);

--changeset admin:016
ALTER TABLE reports
DROP COLUMN worker_lock;

--changeset admin:017
ALTER TABLE notifications
DROP COLUMN  is_sent;

--changeset admin:018
ALTER TABLE notifications
ADD COLUMN is_read BOOLEAN NOT NULL DEFAULT FALSE;

--changeset admin:019
CREATE INDEX idx_income_user_id
ON Income (user_id, date DESC);

--changeset admin:020
CREATE TABLE idempotent_records(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key VARCHAR(255) UNIQUE NOT NULL,
    status VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP
);

CREATE INDEX idx_idempotency_key
ON idempotent_records(idempotency_key);


--changeset admin:021
CREATE INDEX idx_user_email
ON users(email);

--changeset admin:022
ALTER TABLE reports
ADD CONSTRAINT uk_reports_user_id
UNIQUE(user_id)

--changeset admin:023
DROP INDEX idx_reports_user_id




