spring.profiles.active=dev
spring.jpa.open-in-view=false

# Liquibase
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db-changelog.sql

# Hibernate Behavior
spring.jpa.hibernate.ddl-auto=none

jwt.secret=${JWT_SECRET}

# RabbitMQ Retry Logic
spring.rabbitmq.listener.simple.retry.enabled=true
spring.rabbitmq.listener.simple.retry.initial-interval=3000
spring.rabbitmq.listener.simple.retry.max-attempts=3
spring.rabbitmq.listener.simple.retry.multiplier=2.0
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Monitoring
management.metrics.distribution.percentiles.http.server.requests=0.5,0.95,0.99
management.metrics.distribution.percentiles-histogram.http.server.requests=true

# Logging
logging.level.org.hibernate=WARN
logging.level.org.springframework.jdbc=WARN
logging.level.liquibase=WARN