
  spring:
    profiles:
      active: ${SPRING_PROFILES_ACTIVE}
    servlet:
      multipart:
        max-file-size: 5MB
        max-request-size: 5MB
    jpa:
      open-in-view: false
      hibernate:
        ddl-auto: none

    liquibase:
      enabled: true
      change-log: classpath:db/changelog/db-changelog.sql

    rabbitmq:
      listener:
        simple:
          retry:
            enabled: true
            initial-interval: 3000
            max-attempts: 3
            multiplier: 2.0
          default-requeue-rejected: false

  management:
    metrics:
      distribution:
        percentiles:
          http:
            server:
              requests: 0.5,0.95,0.99
        percentiles-histogram:
          http:
            server:
              requests: true


  rate-limiting:
    rules:
      - path: "/auth/login"
        capacity: 10
        refillTokens: 5
        refillMinutes: 15

      - path: "/auth/register"
        capacity: 8
        refillTokens: 1
        refillMinutes: 30

      - path: "/auth/update-account-info"
        capacity: 5
        refillTokens: 1
        refillMinutes: 20

      - path: "/auth/update-password"
        capacity: 3
        refillTokens: 1
        refillMinutes: 60

      - path: "/auth/user-verify"
        capacity: 60
        refillTokens: 20
        refillMinutes: 10

      - path: "/report/generate-report"
        capacity: 3
        refillTokens: 2
        refillMinutes: 60

      - path: "DEFAULT"
        capacity: 60
        refillTokens: 5
        refillMinutes: 10




