# 1. Database:
spring.datasource.url=jdbc:postgresql://${DB_HOST:postgres}:5432/${DB_NAME:expense_db}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# 2. RabbitMQ:
spring.rabbitmq.host=${RABBITMQ_HOST:rabbitmq}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASS:guest}

# 3. Cloudinary:
cloudinary.cloud_name=${CLOUDINARY_NAME}
cloudinary.api_key=${CLOUDINARY_KEY}
cloudinary.api_secret=${CLOUDINARY_SECRET}

# 4. Production safety
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false

# 5. Logging
logging.level.root=INFO
logging.level.com.example.ExpenseTracker=WARN

#Actuator
management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never

spring.jpa.properties.hibernate.jdbc.time_zone=UTC

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=5
spring.datasource.hikari.connection-timeout=30000