
  spring:
    datasource:
      url: ${SPRING_DATASOURCE_URL}
      username: ${SPRING_DATASOURCE_USERNAME}
      password: ${SPRING_DATASOURCE_PASSWORD}
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true

  jwt:
    secret: ${JWT_SECRET}


  springdoc:
    api-docs:
      enabled: true
    swagger-ui:
      enabled: true
      withCredentials: true

  management:
    endpoint:
      startup:
        enabled: true
      health:
        show-details: always
    endpoints:
      web:
        exposure:
          include: "health,metrics,beans,startup"

  cloudinary:
    cloud_name: ${CLOUDINARY_CLOUD_NAME}
    api_key: ${CLOUDINARY_API_KEY}
    api_secret: ${CLOUDINARY_API_SECRET}


  logging:
    level:
      root: INFO
      org.hibernate: WARN
      org.springframework.jdbc: WARN
      liquibase: INFO
      com.example.ExpenseTracker: DEBUG
      com.zaxxer.hikari: INFO


  server:
    tomcat:
      accesslog:
        enabled: true
        directory: C:/Users/USER/Expense-manager-app/backend/logs
        prefix: access_log
        suffix: .log
        pattern: "%h %l %u %t \"%r\" %s %b %D"
